const LOGIN_REQUEST= "LOGIN_REQUEST";
const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
const LOGIN_FAILURE = "LOGIN_FAILURE";

export const loginActions = {
    LOGIN_SUCCESSFUL,
    LOGIN_REQUEST,
    LOGIN_FAILURE
};
